spring:
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: ${DB_URL}gemtries
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}